db:
    image: mysql
    environment:
        MYSQL_ROOT_PASSWORD: ting
        MYSQL_DATABASE: ting

api:
    build: .
    dockerfile: Dockerfile-api
    command: sh -c "python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000"
    links:
        - db

realtime:
    build: .
    dockerfile: Dockerfile-realtime
    ports:
        - "8080:8080"
    links:
        - front

front:
    image: nginx
    volumes:
        - config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
        - .:/usr/src/app/
    ports:
        - "80:80"
    links:
        - api
